export const TOP_STORIES_REQUEST = "TOP_STORIES_REQUEST"
export const TOP_STORIES_SUCCESS = "TOP_STORIES_SUCCESS"

// Video Articles

export const VIDEO_ARTICLE_REQUEST = "VIDEO_ARTICLE_REQUEST"
export const VIDEO_ARTICLE_SUCCESS = "VIDEO_ARTICLE_SUCCESS"

